version: "3.8"

services:
  swagger:
    image: swaggerapi/swagger-ui:latest
    restart: always
    container_name: eon-docs
    ports:
      - 8070:8080
    volumes:
      - ./documentation/swagger.json:/app/swagger.json